services:
  mysql:
    image: mysql:5.7
    volumes:
      - "db:/var/lib/mysql:rw"
      - "./mysqlsampledatabase.sql.gz:/docker-entrypoint-initdb.d/db.sql.gz:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=toor

  percona:
    image: percona/percona-xtrabackup:2.4
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    volumes:
      - "db:/var/lib/mysql"
      - "./my.cnf:/etc/my.cnf:ro"
      - "./mysql-backup:/mysql-backup"

volumes:
  db:

